export enum ACTIONS {
	GET_HEROES = "GET_HEROES",

	SET_HEROES_DC = "SET_HEROES_DC",
	SET_HEROES_DC_SLIDER = "SET_HEROES_DC_SLIDER",

	SET_HEROES_MARVEL = "SET_HEROES_MARVEL",
	SET_HEROES_MARVEL_SLIDER = "SET_HEROES_MARVEL_SLIDER",

	SET_CHOICED_HERO_DC = "SET_CHOICED_HERO_DC",
	SET_CHOICED_HERO_MARVEL = "SET_CHOICED_HERO_MARVEL",

	GET_FIGHTERS = "GET_FIGHTERS",
	SET_FIGHTER_HERO_DC = "SET_FIGHTER_HERO_DC",
	SET_FIGHTER_HERO_MARVEL = "SET_FIGHTER_HERO_MARVEL",

	SET_KIK_COUNT = "SET_KIK_COUNT",
	SET_IS_DISABLED_BTN = "SET_IS_DISABLED_BTN",
	SET_FACE_DC = "SET_FACE_DC",
	SET_FACE_MARVEL = "SET_FACE_MARVEL",
	SET_TABLE_FIGHT = "SET_TABLE_FIGHT",
	SET_ROLLING = "SET_ROLLING",
	SET_REMANING_LIFES = "SET_REMANING_LIFES",
	SET_WINNER = "SET_WINNER",

	GET_DC = "GET_DC",
	SET_DC = "SET_DC",
	SET_DC_PAGINATION = "SET_DC_PAGINATION",
	SET_DC_FITERED_HERO = "SET_DC_FITERED_HERO",

	GET_MARVEL = "GET_MARVEL",
	SET_MARVEL = "SET_MARVEL",
	SET_MARVEL_PAGINATION = "SET_MARVEL_PAGINATION",
	SET_MARVEL_FITERED_HERO = "SET_MARVEL_FITERED_HERO",

	GET_HERO = "GET_HERO",
	SET_HERO = "SET_HERO",

	SET_HISTORY_FIGHT = "SET_HISTORY_FIGHT",
}
